# Site settings
name: Woodmansee Wanderlust
description: 'Depictions and descriptions of our travels'

baseurl: '' # the subpath of your site, e.g. /blog
url: 'http://newmansee.com' # the base hostname & protocol for your site

# Build settings
markdown:            kramdown
relative_permalinks: false
permalink:           :title/

pagination:          true
paginate:            8
paginate_path:       page/:num/

author:
    name: 'Zack Woodmansee'
    email: ''
    uri: 'https://github.com/woodmanzee'

sass:
    sass_dir: _sass
    style:    compressed

defaults:
  -
      scope:
        path: '_posts'
        type: 'posts'
      values:
        reading_time: true
        # Meta
        show_tags: true
        show_categories: true
        # Social
        share_buttons: false
        disqus: true

gems:
    - jekyll-feed
    - jekyll-sitemap
    - jekyll-paginate
